# Task 2

<h3>
1.
Write a function so that the columns of the output matrix are powers of the input vector.<br>
The order of the powers is determined by the increasing boolean argument.<br> Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.<br><br>
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.</h3>

In [2]:
import numpy as np

## Iterate over each number in the input vector n times, n being the number of columns in the o/p matrix and output 
## an intermediate vector. Use diff order formula based on increasing and decreasing condition.
## Reshape the intermediate vector using the size of the input vector (rows) and n (columns) to generate the o/p matrix. 
   
def vander_matrix(ipvector, n):
        vanobj = [x**(n-1-i) for x in ipvector for i in range(n)]
        op_matx = np.array(vanobj).reshape(ipvector.size,n)
        return op_matx

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx = vander_matrix(inputvector,no_col_opmat)

print("The input array is:",inputvector,"\n")
print("Number of columns in output matrix:",no_col_opmat,"\n")
print("AlexandreTheophile Vandermonde Matrix:\n\n",op_matx,"\n")


The input array is: [1 2 3 4 5] 

Number of columns in output matrix: 3 

AlexandreTheophile Vandermonde Matrix:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

