# Task 2

<h3>
1.
Write a function so that the columns of the output matrix are powers of the input vector.<br>
The order of the powers is determined by the increasing boolean argument.<br> Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.<br><br>
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.</h3>

In [1]:
# Without using Numpy
def custom_vander(inp_list, N=None, increasing = False):
    
    if N == None : N = len(inp_list)
    if increasing:
        matrix = [[element**power for power in range(0, N)] for element in inp_list]
        print(matrix)
    else:
        matrix = [[element**power for power in range(N-1, -1, -1)] for element in inp_list]
        print(matrix)

In [2]:
custom_vander([1, 2, 3, 5])

[[1, 1, 1, 1], [8, 4, 2, 1], [27, 9, 3, 1], [125, 25, 5, 1]]


In [4]:
import numpy as np

In [5]:
# With the use of Numpy
def custom_vander_np(inp_list, N=None, increasing = False):
    
    if N == None : N = len(inp_list)
    if increasing:
        matrix = [[element**power for power in range(0, N)] for element in inp_list]
        print(np.row_stack(matrix))
    else:
        matrix = [[element**power for power in range(N-1, -1, -1)] for element in inp_list]
        print(np.row_stack(matrix))

In [6]:
custom_vander_np([1, 2, 3, 5])

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [7]:
custom_vander_np([1, 2, 3, 5], N = 5)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [625 125  25   5   1]]


In [8]:
custom_vander_np([1, 2, 3, 5], increasing = True)

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]
