<strong>Problem Statement 1:</strong><br>
Write a function so that the columns of the output matrix are powers of the input<br>
vector.<br><br>
The order of the powers is determined by the increasing boolean argument. Specifically, when<br>
increasing is False, the i-th output column is the input vector raised element-wise to the power<br>
of N - i - 1.<br><br>
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde

In [11]:
import numpy as np

def vandermonde_matrix(inpt, N = None, increasing = False):
    if N==None:
        N = len(inpt)
    if increasing:
        result = [[pow(elmnt, power) for power in range(0, N)] for elmnt in inpt]
        print(np.asanyarray(result))
    else:
        result = [[pow(elmnt, power) for power in range(N-1, -1, -1) ] for elmnt in inpt]
        print(np.asanyarray(result))      

In [12]:
inpt = [1,2,3,5]        
vandermonde_matrix(inpt,increasing = False)  

[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [125  25   5   1]]


In [13]:
vandermonde_matrix(inpt, increasing = True)

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


<br><br><br><strong>Problem Statement 2:</strong><br>
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:<br>
The moving average sequence has n-k+1 elements as shown below.<br>
The moving averages with k=4 of a ten-value sequence (n=10) is shown below<br>
i 1 2 3 4 5 6 7 8 9 10<br><br>
===== == == == == == == == == == ==<br><br>
Input 10 20 30 40 50 60 70 80 90 100<br><br>
y1 25 = (10+20+30+40)/4<br><br>
y2 35 = (20+30+40+50)/4<br><br>
y3 45 = (30+40+50+60)/4<br><br>
y4 55 = (40+50+60+70)/4<br><br>
y5 65 = (50+60+70+80)/4<br><br>
y6 75 = (60+70+80+90)/4<br><br>
y7 85 = (70+80+90+100)/4<br><br>
Thus, the moving average sequence has n-k+1=10-4+1=7 values.<br>
<strong>Question:</strong> Write a function to find moving average in an array over a window:<br><br>
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [2]:
def mov_avg_val(mylist, N):
    cumsum, moving_avgs = [0], []
    
    for i, x in enumerate(mylist, 1):
        cumsum.append(cumsum[i-1] + x)
        if i>=N:
            moving_avg = round(((cumsum[i] - cumsum[i-N])/N),2)
            moving_avgs.append(moving_avg)
    
    print("Moving average: ", moving_avgs)
    print("Length of the list l-N+1: ", len(moving_avgs))

In [3]:
l = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = 3
mov_avg_val(l,n)

Moving average:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of the list l-N+1:  11
